project_id = "uswgppmnvxgjptzgqsoq"

[functions.weather]
verify_jwt = false

[functions.markets]
verify_jwt = false

[functions.news]
verify_jwt = false

[functions.sports]
verify_jwt = false

[functions.transport]
verify_jwt = false

[functions.money]
verify_jwt = false
