export type HeroShape = "reactor" | "shield" | "hammer" | "arrow" | "gamma" | "web" | "cloak" | "wing" | "star" | "orb";

export interface Hero {
  slug: string;
  name: string;
  alias: string;
  shape: HeroShape;
  colorA: string;
  colorB: string;
  tagline: string;
  bio: string;
  species: string;
  affiliation: string[];
  firstAppearance: string;
  base: string;
  powers: string[];
  gear: string[];
  weaknesses: string[];
  stats: { power: number; intellect: number; speed: number; durability: number; combat: number; energy: number };
  films: string[];
  quotes: string[];
}

export const HEROES: Hero[] = [
  {
    slug: "iron-man",
    name: "Tony Stark",
    alias: "Iron Man",
    shape: "reactor",
    colorA: "#ff3b30",
    colorB: "#ffd60a",
    tagline: "Genius. Billionaire. Playboy. Philanthropist.",
    bio: "Weapons magnate turned armored defender after building the first Mark suit in a cave with a box of scraps. Founder-financier of the Avengers Initiative and architect of the Sokovia Accords debate.",
    species: "Human (augmented by technology)",
    affiliation: ["Avengers", "Stark Industries", "S.H.I.E.L.D. consultant"],
    firstAppearance: "Tales of Suspense #39 (1963)",
    base: "Stark Tower, New York",
    powers: ["Genius-level engineering", "Powered exoskeleton flight", "Repulsor energy projection", "Tactical AI integration"],
    gear: ["Mark LXXXV nanotech armor", "Arc reactor", "F.R.I.D.A.Y. / J.A.R.V.I.S.", "Nano gauntlet"],
    weaknesses: ["Shrapnel-scarred heart", "Reactor power ceiling", "Impulsiveness"],
    stats: { power: 82, intellect: 100, speed: 74, durability: 85, combat: 72, energy: 92 },
    films: ["Iron Man", "The Avengers", "Civil War", "Infinity War", "Endgame"],
    quotes: ["I am Iron Man.", "Sometimes you gotta run before you can walk."],
  },
  {
    slug: "captain-america",
    name: "Steve Rogers",
    alias: "Captain America",
    shape: "shield",
    colorA: "#2f6fe0",
    colorB: "#ff3b30",
    tagline: "I can do this all day.",
    bio: "A frail volunteer transformed by the Super Soldier Serum into the moral spine of the Avengers, frozen for decades and thawed into a world he refuses to let lose its principles.",
    species: "Human (Super Soldier Serum)",
    affiliation: ["Avengers", "S.H.I.E.L.D.", "Howling Commandos"],
    firstAppearance: "Captain America Comics #1 (1941)",
    base: "Avengers Compound, Upstate New York",
    powers: ["Peak human strength and stamina", "Accelerated healing", "Master tactician", "Vibranium shield mastery"],
    gear: ["Vibranium shield", "Wakandan energy shields", "Mjolnir (worthy)"],
    weaknesses: ["No superhuman durability", "Unyielding idealism"],
    stats: { power: 70, intellect: 78, speed: 68, durability: 72, combat: 100, energy: 30 },
    films: ["The First Avenger", "The Winter Soldier", "Civil War", "Endgame"],
    quotes: ["I could do this all day.", "Avengers… assemble."],
  },
  {
    slug: "thor",
    name: "Thor Odinson",
    alias: "God of Thunder",
    shape: "hammer",
    colorA: "#4fc3f7",
    colorB: "#b388ff",
    tagline: "Bring me Thanos.",
    bio: "Crown prince of Asgard, wielder of storm and lightning, humbled into heroism and reforged as the last king of a people rather than a place.",
    species: "Asgardian",
    affiliation: ["Avengers", "Asgard", "Guardians of the Galaxy"],
    firstAppearance: "Journey into Mystery #83 (1962)",
    base: "New Asgard, Norway",
    powers: ["Storm and lightning control", "Godlike strength", "Extended lifespan", "Flight via weapon"],
    gear: ["Mjolnir", "Stormbreaker", "Bifrost access"],
    weaknesses: ["Grief and self-doubt", "Overconfidence"],
    stats: { power: 100, intellect: 70, speed: 83, durability: 96, combat: 88, energy: 98 },
    films: ["Thor", "Ragnarok", "Infinity War", "Endgame", "Love and Thunder"],
    quotes: ["I am Thor, son of Odin.", "You should have gone for the head."],
  },
  {
    slug: "hulk",
    name: "Bruce Banner",
    alias: "Hulk",
    shape: "gamma",
    colorA: "#57d16a",
    colorB: "#7c4dff",
    tagline: "That's my secret — I'm always angry.",
    bio: "A gamma physicist bonded to an indestructible force of rage, who eventually negotiated peace between mind and monster to become Smart Hulk.",
    species: "Human mutate (gamma radiation)",
    affiliation: ["Avengers", "Culver University"],
    firstAppearance: "The Incredible Hulk #1 (1962)",
    base: "Avengers Compound",
    powers: ["Limitless strength scaling with rage", "Regeneration", "Radiation immunity", "Seven PhDs"],
    gear: ["Gamma-tolerant nano gauntlet", "Hulkbuster co-pilot rig"],
    weaknesses: ["Emotional control", "Vulnerable in Banner form"],
    stats: { power: 98, intellect: 88, speed: 63, durability: 100, combat: 74, energy: 55 },
    films: ["The Incredible Hulk", "The Avengers", "Ragnarok", "Endgame"],
    quotes: ["Hulk smash.", "I'm always angry."],
  },
  {
    slug: "black-widow",
    name: "Natasha Romanoff",
    alias: "Black Widow",
    shape: "orb",
    colorA: "#ff5252",
    colorB: "#212121",
    tagline: "I've got red in my ledger.",
    bio: "Red Room graduate turned S.H.I.E.L.D. operative, the Avengers' conscience in the shadows, who traded her life on Vormir for the Soul Stone.",
    species: "Human (chemically enhanced)",
    affiliation: ["Avengers", "S.H.I.E.L.D.", "Red Room (former)"],
    firstAppearance: "Tales of Suspense #52 (1964)",
    base: "Avengers Compound",
    powers: ["Master espionage", "Peak acrobatics", "Multilingual interrogation", "Marksmanship"],
    gear: ["Widow's Bite gauntlets", "Glock batons", "Grapple line"],
    weaknesses: ["Baseline human durability", "Haunted by her past"],
    stats: { power: 48, intellect: 82, speed: 70, durability: 45, combat: 94, energy: 25 },
    films: ["Iron Man 2", "The Avengers", "Black Widow", "Endgame"],
    quotes: ["I'm always picking up after you boys.", "See you in a minute."],
  },
  {
    slug: "hawkeye",
    name: "Clint Barton",
    alias: "Hawkeye",
    shape: "arrow",
    colorA: "#9c27b0",
    colorB: "#4caf50",
    tagline: "Never miss.",
    bio: "The Avenger with no powers and no margin for error — a S.H.I.E.L.D. marksman whose family kept him human through the Blip and beyond.",
    species: "Human",
    affiliation: ["Avengers", "S.H.I.E.L.D."],
    firstAppearance: "Tales of Suspense #57 (1964)",
    base: "Barton Farm, Missouri",
    powers: ["Perfect marksmanship", "Master of edged weapons", "Tactical improvisation"],
    gear: ["Recurve combat bow", "Trick arrow quiver", "Ronin blade"],
    weaknesses: ["No enhancements", "Hearing loss"],
    stats: { power: 42, intellect: 72, speed: 62, durability: 44, combat: 92, energy: 20 },
    films: ["Thor", "The Avengers", "Age of Ultron", "Endgame"],
    quotes: ["The city is flying and we're fighting an army of robots.", "Don't mistake patience for hesitation."],
  },
  {
    slug: "spider-man",
    name: "Peter Parker",
    alias: "Spider-Man",
    shape: "web",
    colorA: "#e53935",
    colorB: "#1e88e5",
    tagline: "Your friendly neighborhood Spider-Man.",
    bio: "A Queens teenager bitten by a radioactive spider, mentored by Stark, and left to rebuild an identity the world has forgotten.",
    species: "Human mutate",
    affiliation: ["Avengers", "Midtown School of Science"],
    firstAppearance: "Amazing Fantasy #15 (1962)",
    base: "Queens, New York",
    powers: ["Wall-crawling", "Spider-sense", "Proportionate strength and agility", "Genius chemistry"],
    gear: ["Web-shooters", "Iron Spider armor", "Stark drone lenses"],
    weaknesses: ["Inexperience", "Divided civilian life"],
    stats: { power: 76, intellect: 90, speed: 88, durability: 68, combat: 82, energy: 40 },
    films: ["Civil War", "Homecoming", "Infinity War", "No Way Home"],
    quotes: ["With great power comes great responsibility.", "Mr. Stark, I don't feel so good."],
  },
  {
    slug: "black-panther",
    name: "T'Challa",
    alias: "Black Panther",
    shape: "cloak",
    colorA: "#7e57c2",
    colorB: "#212121",
    tagline: "Wakanda forever.",
    bio: "King of Wakanda and bearer of the Heart-Shaped Herb, who opened the world's most advanced nation to a planet that never knew it existed.",
    species: "Human (herb-enhanced)",
    affiliation: ["Avengers", "Wakanda", "Dora Milaje"],
    firstAppearance: "Fantastic Four #52 (1966)",
    base: "Golden City, Wakanda",
    powers: ["Enhanced strength and reflexes", "Kinetic energy absorption", "Master strategist"],
    gear: ["Vibranium habit", "Kimoyo beads", "Panther claws"],
    weaknesses: ["Duty over instinct", "Herb dependency"],
    stats: { power: 74, intellect: 88, speed: 78, durability: 80, combat: 90, energy: 60 },
    films: ["Civil War", "Black Panther", "Infinity War", "Endgame"],
    quotes: ["In my culture, death is not the end.", "Wakanda forever."],
  },
  {
    slug: "doctor-strange",
    name: "Stephen Strange",
    alias: "Doctor Strange",
    shape: "orb",
    colorA: "#ff7043",
    colorB: "#26c6da",
    tagline: "14,000,605 futures.",
    bio: "A neurosurgeon whose ruined hands led him to Kamar-Taj, now Master of the Mystic Arts and guardian of the Time Stone's legacy.",
    species: "Human sorcerer",
    affiliation: ["Masters of the Mystic Arts", "Avengers"],
    firstAppearance: "Strange Tales #110 (1963)",
    base: "Sanctum Sanctorum, New York",
    powers: ["Mystic energy manipulation", "Portal creation", "Astral projection", "Time manipulation"],
    gear: ["Cloak of Levitation", "Eye of Agamotto", "Sling Ring"],
    weaknesses: ["Damaged hands", "Arrogance"],
    stats: { power: 92, intellect: 96, speed: 70, durability: 62, combat: 78, energy: 100 },
    films: ["Doctor Strange", "Infinity War", "Endgame", "Multiverse of Madness"],
    quotes: ["We're in the endgame now.", "Dormammu, I've come to bargain."],
  },
  {
    slug: "scarlet-witch",
    name: "Wanda Maximoff",
    alias: "Scarlet Witch",
    shape: "orb",
    colorA: "#e53935",
    colorB: "#ff8a65",
    tagline: "You took everything from me.",
    bio: "Sokovian volunteer exposed to the Mind Stone, whose chaos magic makes her the single most powerful being the Avengers ever fought beside.",
    species: "Human (Mind Stone enhanced witch)",
    affiliation: ["Avengers", "HYDRA (former)"],
    firstAppearance: "X-Men #4 (1964)",
    base: "Westview, New Jersey",
    powers: ["Chaos magic", "Telekinesis", "Reality alteration", "Mental manipulation"],
    gear: ["Darkhold (former)", "Mind Stone tiara"],
    weaknesses: ["Grief-driven instability"],
    stats: { power: 100, intellect: 74, speed: 76, durability: 70, combat: 68, energy: 100 },
    films: ["Age of Ultron", "Civil War", "Infinity War", "WandaVision"],
    quotes: ["You took everything from me.", "I don't need you to tell me who I am."],
  },
  {
    slug: "vision",
    name: "Vision",
    alias: "Vision",
    shape: "star",
    colorA: "#f4c430",
    colorB: "#ba68c8",
    tagline: "A thing isn't beautiful because it lasts.",
    bio: "A synthezoid born of J.A.R.V.I.S., Ultron's frame and the Mind Stone — proof that the Avengers could create as well as destroy.",
    species: "Synthezoid",
    affiliation: ["Avengers"],
    firstAppearance: "The Avengers #57 (1968)",
    base: "Avengers Compound",
    powers: ["Density manipulation", "Mind Stone beam", "Flight", "Superhuman computation"],
    gear: ["Mind Stone", "Vibranium body"],
    weaknesses: ["Stone dependency", "Naivety about humanity"],
    stats: { power: 90, intellect: 96, speed: 82, durability: 88, combat: 70, energy: 96 },
    films: ["Age of Ultron", "Civil War", "Infinity War", "WandaVision"],
    quotes: ["A thing isn't beautiful because it lasts.", "I am… I am."],
  },
  {
    slug: "falcon",
    name: "Sam Wilson",
    alias: "Falcon / Captain America",
    shape: "wing",
    colorA: "#ef6c00",
    colorB: "#90a4ae",
    tagline: "On your left.",
    bio: "Pararescue veteran turned wingman, who inherited the shield and the harder job of making it mean something to everyone.",
    species: "Human",
    affiliation: ["Avengers", "USAF (former)"],
    firstAppearance: "Captain America #117 (1969)",
    base: "Delacroix, Louisiana",
    powers: ["Aerial combat mastery", "Counselling and de-escalation", "Marksmanship"],
    gear: ["EXO-7 / Wakandan wing harness", "Redwing drone", "Vibranium shield"],
    weaknesses: ["Baseline human", "Equipment-dependent flight"],
    stats: { power: 52, intellect: 76, speed: 80, durability: 50, combat: 84, energy: 35 },
    films: ["The Winter Soldier", "Civil War", "Endgame", "Falcon and the Winter Soldier"],
    quotes: ["On your left.", "I'm just a guy who keeps his promises."],
  },
];

export const getHero = (slug?: string) => HEROES.find((h) => h.slug === slug);
