// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yufxcjjhltklghwylzzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1ZnhjampobHRrbGdod3lsenpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3MTk4OTksImV4cCI6MjA4NDI5NTg5OX0.0xqASVOZtHrFA1gR7oHcpM4cYQS9OnR3e4Rh7KKdPV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});